name: pull-request

on:
  pull_request:
    branches: [master]

jobs:
  checks:
    name: Check - ${{ matrix.check }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: ["test", "lint:check", "type-check"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Install dependencies
        run: pnpm install --ignore-scripts

      - name: Run check
        run: pnpm run ${{ matrix.check }}